CREATE TABLE `country` (
  `ID` int(11) NOT NULL,
  `COUNTRY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `employee` (
  `ID` varchar(10) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ID_COUNTRY` int(11) DEFAULT NULL,
  `SECTOR` varchar(100) DEFAULT NULL,
  `JRSS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `EMPLOYEE_COUNTRY_idx` (`ID_COUNTRY`),
  CONSTRAINT `EMPLOYEE_COUNTRY` FOREIGN KEY (`ID_COUNTRY`) REFERENCES `country` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `manager` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `week` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NUM_WEEK` int(10) DEFAULT NULL,
  `START_DATE` date NOT NULL,
  `END_DATE` date NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

CREATE TABLE `assignment` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_NAME` varchar(100) DEFAULT NULL,
  `CLIENT_NAME` varchar(100) DEFAULT NULL,
  `ID_COUNTRY` int(11) DEFAULT NULL,
  `INDUSTRY` varchar(100) DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `ID_MANAGER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `ASSIGNMENT_MANAGER_idx` (`ID_MANAGER`),
  KEY `ASSIGNMENT_COUNTRY_idx` (`ID_COUNTRY`),
  CONSTRAINT `ASSIGNMENT_COUNTRY` FOREIGN KEY (`ID_COUNTRY`) REFERENCES `country` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ASSIGNMENT_MANAGER` FOREIGN KEY (`ID_MANAGER`) REFERENCES `manager` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `work` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ID_EMPLOYEE` varchar(10) NOT NULL,
  `ID_WEEK` int(10) NOT NULL,
  `ID_ASSIGNMENT` int(10) NOT NULL,
  `HOURS_X_WEEK` int(10) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `work_employee_idx` (`ID_EMPLOYEE`),
  KEY `work_week_idx` (`ID_WEEK`),
  KEY `WORK_ASSIGNMENT_idx` (`ID_ASSIGNMENT`),
  CONSTRAINT `WORK_ASSIGNMENT` FOREIGN KEY (`ID_ASSIGNMENT`) REFERENCES `assignment` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `work_employee` FOREIGN KEY (`ID_EMPLOYEE`) REFERENCES `employee` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `work_week` FOREIGN KEY (`ID_WEEK`) REFERENCES `week` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1521 DEFAULT CHARSET=latin1;

CREATE TABLE `work_history` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ID_EMPLOYEE` varchar(10) NOT NULL,
  `ID_WEEK` int(10) NOT NULL,
  `ID_ASSIGNMENT` int(10) NOT NULL,
  `HOURS_X_WEEK` int(10) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `work_his_employee_idx` (`ID_EMPLOYEE`),
  KEY `work_his_week_idx` (`ID_WEEK`),
  KEY `WORK_HIS_ASSIGNMENT_idx` (`ID_ASSIGNMENT`),
  CONSTRAINT `WORK_HIS_ASSIGNMENT` FOREIGN KEY (`ID_ASSIGNMENT`) REFERENCES `assignment` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `work_his_employee` FOREIGN KEY (`ID_EMPLOYEE`) REFERENCES `employee` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `work_his_week` FOREIGN KEY (`ID_WEEK`) REFERENCES `week` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1521 DEFAULT CHARSET=latin1;

CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (username));

CREATE TABLE user_roles (
  user_role_id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uni_username_role (role,username),
  KEY fk_username_idx (username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));
  
  
CREATE TABLE `holiday`(
	`ID`int(10) not null AUTO_INCREMENT,
	`DESCRIPTION` varchar(100) not null ,
	`DATE` date NOT NULL,
	PRIMARY KEY(`ID`)
);
CREATE TABLE Country_has_Holiday(
    CountryID INT NOT NULL,
    HolidayID INT NOT NULL,
    FOREIGN KEY (CountryID) REFERENCES Country (ID),
    FOREIGN KEY (HolidayID) REFERENCES Holiday (ID)    
);


